stages:
  - Deploy Production

deploy to production:
  only:
      refs:
        - main
  stage: Deploy Production
  tags:
    - internal
    - taiga
    - outline
    - betacoreapi
  before_script:
    - sudo cd $PRODUCTION_DIR
  script:
    - whoami
    - sudo git config --global --add safe.directory $PRODUCTION_DIR
    - sudo git pull http://$GIT_USER:$GIT_PASS@dev.fast-8.com:9874/FAST-8/taiga-points.git master
    - sudo git branch
    - sudo git status
    - docker-compose up -d --build
